version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: worktrackr-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: worktrackr
      POSTGRES_PASSWORD: worktrackr
      POSTGRES_DB: worktrackr
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
